# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce  Org


# On Push to Master/Main this will be triggered.
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your juji8ob can access it
    - uses: actions/checkout@v2

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: 14
    
    # Install SFDX CLI
    - name: Install SFDX CLI
      run: npm install sfdx-cli --global

    # Authorize SF Org
    - name: Authorize SF Org
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
        INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
   

      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile  ./buildfiles/server.key  --username $SALESFORCE_USERNAME --instanceurl $INSTANCE_URL
      
          # Convert to Deploy Source
    - name: Convert to Deploy Source
      run: sfdx force:source:convert -r ./force-app -d ./toDeploy
    
    # Run Validation of Deploy Source
    - name: Run Validation on Deploy Source
      run: sfdx force:source:deploy -c -x manifest/package.xml -u Dev1
    
    # Deploy
    - name : Deploy to SF Org            
      run: sfdx force:source:deploy -x manifest/package.xml -u Dev1
